import { ArrowRight, Brain, Heart, ShieldCheck, Sparkles } from 'lucide-react'
import { motion } from 'motion/react'
import { PipMascot } from '../components/PipMascot'
import { Card, Eyebrow, LinkButton } from '../components/ui'

export default function Home() {
  return <>
    <section className="hero section"><div className="hero-copy"><Eyebrow><Sparkles size={15} /> One paw at a time</Eyebrow><h1>Feel safer around dogs.<br/><em>One small step at a time.</em></h1><p className="lead">Learn what dogs may be communicating, what to do when you encounter one, and how to build confidence without rushing yourself.</p><div className="button-row"><LinkButton to="/onboarding">Start learning <ArrowRight size={18} /></LinkButton><LinkButton to="/owners" variant="secondary">I’m a dog owner</LinkButton></div><p className="reassurance">You set the pace. Interaction is always optional.</p></div><motion.div className="hero-art" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="sun"/><div className="cloud cloud-one"/><div className="cloud cloud-two"/><PipMascot mood="calm" size={330} label="Pip, a friendly illustrated dog, sitting at a comfortable distance"/><span className="distance-note">A comfortable distance 💛</span></motion.div></section>
    <section className="section problem-section"><div className="section-heading"><Eyebrow>Both things can be true</Eyebrow><h2>A dog may be friendly.<br/>You may still feel nervous.</h2><p>Pawsitive helps people understand dogs—and helps dog owners understand people.</p></div><div className="perspective-cards"><Card className="perspective nervous"><span className="big-icon">😰</span><small>Person</small><h3>“I don’t know what this dog is going to do.”</h3></Card><div className="perspective-bridge"><span>🐾</span><strong>Same moment.<br/>Two perspectives.</strong></div><Card className="perspective owner"><span className="big-icon">🐶</span><small>Owner</small><h3>“My dog is friendly. Why are they moving away?”</h3></Card></div></section>
    <section className="section values"><div className="section-heading"><Eyebrow>How it works</Eyebrow><h2>Understanding makes encounters feel less unpredictable.</h2></div><div className="three-grid"><Card><span className="feature-icon blue"><Brain /></span><h3>Understand</h3><p>Learn what common dog behaviours can mean—in context.</p></Card><Card><span className="feature-icon coral"><ShieldCheck /></span><h3>Respond</h3><p>Practise calm, practical choices for real situations.</p></Card><Card><span className="feature-icon mint"><Heart /></span><h3>Build confidence</h3><p>Make progress gently, without forced exposure.</p></Card></div></section>
    <section className="section final-cta"><PipMascot mood="happy" size={175}/><div><Eyebrow>Ready when you are</Eyebrow><h2>A little understanding can make the next encounter easier.</h2><LinkButton to="/onboarding">Start your journey <ArrowRight size={18}/></LinkButton></div></section>
  </>
}
